[package]
name = "QuizModule"
version = "1.0.0"
authors = ["Shreyansh"]

[addresses]
QuizModule = "0xcd94a5cf1dbdf28bd26a5d8e04bba5ea43dc7e14b3327ce6e55de346248a818b"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
